import { getConfig } from "@/lib/config";
import type { StepTemplate } from "@/types/task-config";

function t(
  id: string,
  label: string,
  subagent: string,
  category: string,
  display_text: string,
  llm_prompt: string
): StepTemplate {
  return { id, label, subagent, category, display_text, llm_prompt };
}

function appName(): string {
  return getConfig("appName");
}

export function getStepTemplates(): StepTemplate[] {
  const name = appName();
  return [
  // ── User Input ──────────────────────────────────────────────────────
  t("user-input-collect", "Collect User Input", "user_input", name,
    "Collect user input",
    "Collect the following information from the user and write to /request.txt:\n- field_name (required): Description\n\nFormat as key=value. Write to /request.txt."),

  // ── GitHub ──────────────────────────────────────────────────────────
  t("github-get-me", "Get Authenticated User", "github", "GitHub",
    "Get current authenticated user info", "Use get_me to retrieve the current authenticated user info."),
  t("github-get-team-members", "Get Team Members", "github", "GitHub",
    "Get members of a team", "Use get_team_members to list members of team <team_slug> in org <org>."),
  t("github-get-teams", "List Teams", "github", "GitHub",
    "List teams in an organization", "Use get_teams to list all teams in org <org>."),
  t("github-list-issues", "List Issues", "github", "GitHub",
    "List issues in a repository", "Use list_issues to list issues in <org>/<repo>."),
  t("github-search-issues", "Search Issues", "github", "GitHub",
    "Search issues across repositories", "Use search_issues with query \"<query>\" to find matching issues."),
  t("github-issue-read", "Read Issue", "github", "GitHub",
    "Read issue details", "Use issue_read to get details of issue #<number> in <org>/<repo>."),
  t("github-issue-write", "Create/Update Issue", "github", "GitHub",
    "Create or update an issue", "Use issue_write to create or update an issue in <org>/<repo>."),
  t("github-add-issue-comment", "Add Issue Comment", "github", "GitHub",
    "Add a comment to an issue", "Use add_issue_comment to comment on issue #<number> in <org>/<repo>."),
  t("github-list-prs", "List Pull Requests", "github", "GitHub",
    "List pull requests in a repository", "Use list_pull_requests to list PRs in <org>/<repo>."),
  t("github-pr-read", "Read Pull Request", "github", "GitHub",
    "Read pull request details", "Use pull_request_read to get details of PR #<number> in <org>/<repo>."),
  t("github-search-prs", "Search Pull Requests", "github", "GitHub",
    "Search pull requests", "Use search_pull_requests with query \"<query>\" to find matching PRs."),
  t("github-create-pr", "Create Pull Request", "github", "GitHub",
    "Create a pull request", "Use create_pull_request in <org>/<repo> with title, body, head branch and base branch.\nWrite the PR URL to /pr_result.txt."),
  t("github-update-pr", "Update Pull Request", "github", "GitHub",
    "Update an existing pull request", "Use update_pull_request to update PR #<number> in <org>/<repo>."),
  t("github-merge-pr", "Merge Pull Request", "github", "GitHub",
    "Merge a pull request", "Read /pr_result.txt.\nUse merge_pull_request to merge the PR using squash strategy."),
  t("github-pr-review", "Create PR Review", "github", "GitHub",
    "Create or submit a pull request review", "Use pull_request_review_write to review PR #<number> in <org>/<repo>."),
  t("github-update-pr-branch", "Update PR Branch", "github", "GitHub",
    "Update a pull request branch", "Use update_pull_request_branch for PR #<number> in <org>/<repo>."),
  t("github-get-file", "Get File Contents", "github", "GitHub",
    "Get file or directory contents", "Use get_file_contents to read <path> from <org>/<repo> (main branch).\nWrite the content to /template.txt."),
  t("github-create-update-file", "Create/Update File", "github", "GitHub",
    "Create or update a file in a repo", "Use create_or_update_file to write content to <path> in <org>/<repo> on branch <branch>."),
  t("github-push-files", "Push Multiple Files", "github", "GitHub",
    "Push multiple files in a single commit", "Use push_files to commit multiple files to <org>/<repo> on branch <branch>."),
  t("github-delete-file", "Delete File", "github", "GitHub",
    "Delete a file from a repository", "Use delete_file to remove <path> from <org>/<repo> on branch <branch>."),
  t("github-create-branch", "Create Branch", "github", "GitHub",
    "Create a branch in a repository", "Use create_branch to create branch <branch_name> from main in <org>/<repo>.\nWrite the result to /branch_result.txt."),
  t("github-list-branches", "List Branches", "github", "GitHub",
    "List branches in a repository", "Use list_branches to list all branches in <org>/<repo>."),
  t("github-list-commits", "List Commits", "github", "GitHub",
    "List commits in a repository", "Use list_commits to list recent commits in <org>/<repo>."),
  t("github-get-commit", "Get Commit Details", "github", "GitHub",
    "Get details of a specific commit", "Use get_commit to get details of commit <sha> in <org>/<repo>."),
  t("github-create-repo", "Create Repository", "github", "GitHub",
    "Create a new repository", "Use create_repository to create a new repo named <name> in org <org>."),
  t("github-search-repos", "Search Repositories", "github", "GitHub",
    "Search repositories", "Use search_repositories with query \"<query>\" to find matching repositories."),
  t("github-search-code", "Search Code", "github", "GitHub",
    "Search code across repositories", "Use search_code with query \"<query>\" to find matching code."),
  t("github-search-users", "Search Users", "github", "GitHub",
    "Search GitHub users", "Use search_users with query \"<query>\" to find matching users."),
  t("github-fork-repo", "Fork Repository", "github", "GitHub",
    "Fork a repository", "Use fork_repository to fork <org>/<repo>."),
  t("github-get-repo-tree", "Get Repository Tree", "github", "GitHub",
    "Get full repository tree", "Use get_repository_tree to get the file tree of <org>/<repo>."),
  t("github-get-latest-release", "Get Latest Release", "github", "GitHub",
    "Get the latest release", "Use get_latest_release to get the latest release of <org>/<repo>."),
  t("github-list-releases", "List Releases", "github", "GitHub",
    "List all releases", "Use list_releases to list releases of <org>/<repo>."),
  t("github-list-tags", "List Tags", "github", "GitHub",
    "List tags in a repository", "Use list_tags to list tags in <org>/<repo>."),
  t("github-invite-user", "Invite User to Org", "github", "GitHub",
    "Invite a user to an organization", "Use invite_user_to_org to invite <username> to org <org>."),
  t("github-list-labels", "List Labels", "github", "GitHub",
    "List labels in a repository", "Use list_label to list labels in <org>/<repo>."),
  t("github-label-write", "Create/Update Label", "github", "GitHub",
    "Create or update a label", "Use label_write to create or update a label in <org>/<repo>."),
  t("github-list-discussions", "List Discussions", "github", "GitHub",
    "List discussions in a repository", "Use list_discussions to list discussions in <org>/<repo>."),
  t("github-actions-list", "List GitHub Actions", "github", "GitHub",
    "List GitHub Actions workflows", "Use actions_list to list workflows in <org>/<repo>."),
  t("github-actions-trigger", "Trigger Workflow Run", "github", "GitHub",
    "Trigger a GitHub Actions workflow", "Use actions_run_trigger to trigger workflow <workflow_id> in <org>/<repo>."),
  t("github-get-job-logs", "Get Action Job Logs", "github", "GitHub",
    "Get logs from a workflow job", "Use get_job_logs to retrieve logs for job <job_id> in <org>/<repo>."),
  t("github-projects-list", "List Projects", "github", "GitHub",
    "List GitHub Projects", "Use projects_list to list projects in <org>/<repo>."),
  t("github-projects-write", "Update Project Items", "github", "GitHub",
    "Add/update/delete project items", "Use projects_write to manage items in project <project_id>."),
  t("github-list-notifications", "List Notifications", "github", "GitHub",
    "List notifications", "Use list_notifications to list current GitHub notifications."),
  t("github-security-advisories", "List Security Advisories", "github", "GitHub",
    "List security advisories", "Use list_repository_security_advisories for <org>/<repo>."),
  t("github-secret-scanning", "List Secret Scanning Alerts", "github", "GitHub",
    "List secret scanning alerts", "Use list_secret_scanning_alerts for <org>/<repo>."),
  t("github-code-scanning", "List Code Scanning Alerts", "github", "GitHub",
    "List code scanning alerts", "Use list_code_scanning_alerts for <org>/<repo>."),
  t("github-dependabot", "List Dependabot Alerts", "github", "GitHub",
    "List Dependabot alerts", "Use list_dependabot_alerts for <org>/<repo>."),
  t("github-gist-create", "Create Gist", "github", "GitHub",
    "Create a new gist", "Use create_gist with description and files."),
  t("github-gh-cli", "Execute gh CLI", "github", "GitHub",
    "Run a gh CLI command", "Use gh_cli_execute to run: gh <command>."),

  // ── Jira ────────────────────────────────────────────────────────────
  t("jira-get-issue", "Get Issue", "jira", "Jira",
    "Get Jira issue details", "Use get_issue to get details of issue <issue_key>."),
  t("jira-create-issue", "Create Issue", "jira", "Jira",
    "Create a Jira issue", "Read /request.txt.\nUse create_issue in project <project_key> with summary, description, and assignee.\nWrite the issue key to /jira_result.txt."),
  t("jira-update-issue", "Update Issue", "jira", "Jira",
    "Update a Jira issue", "Use update_issue to update issue <issue_key> with new fields."),
  t("jira-search", "JQL Search", "jira", "Jira",
    "Search Jira with JQL", "Use search with JQL query: \"<jql_query>\"."),
  t("jira-transition", "Transition Issue", "jira", "Jira",
    "Transition an issue to a new status", "Read /jira_result.txt.\nUse transition_issue to move the issue to \"<status>\" status."),
  t("jira-get-transitions", "Get Transitions", "jira", "Jira",
    "Get available transitions for an issue", "Use get_transitions for issue <issue_key>."),
  t("jira-add-comment", "Add Comment", "jira", "Jira",
    "Add a comment to a Jira issue", "Use add_comment to add a comment to issue <issue_key>."),
  t("jira-get-comments", "Get Comments", "jira", "Jira",
    "Get comments on a Jira issue", "Use get_comments for issue <issue_key>."),
  t("jira-link-epic", "Link to Epic", "jira", "Jira",
    "Link an issue to an epic", "Use link_to_epic to link issue <issue_key> to epic <epic_key>."),
  t("jira-get-epic-issues", "Get Epic Issues", "jira", "Jira",
    "Get all issues in an epic", "Use get_epic_issues for epic <epic_key>."),
  t("jira-create-link", "Create Issue Link", "jira", "Jira",
    "Link two issues together", "Use create_issue_link to link <issue_key_1> to <issue_key_2>."),
  t("jira-list-projects", "List Projects", "jira", "Jira",
    "List Jira projects", "Use list_projects to list all accessible Jira projects."),
  t("jira-get-project", "Get Project", "jira", "Jira",
    "Get Jira project details", "Use get_project for project <project_key>."),
  t("jira-add-worklog", "Add Worklog", "jira", "Jira",
    "Add a worklog entry", "Use add_worklog to log time on issue <issue_key>."),
  t("jira-create-sprint", "Create Sprint", "jira", "Jira",
    "Create a new sprint", "Use create_sprint on board <board_id> with name <sprint_name>."),
  t("jira-get-sprint-issues", "Get Sprint Issues", "jira", "Jira",
    "Get issues in a sprint", "Use get_sprint_issues for sprint <sprint_id>."),
  t("jira-move-to-sprint", "Move Issues to Sprint", "jira", "Jira",
    "Move issues into a sprint", "Use move_issues_to_sprint to move issues to sprint <sprint_id>."),
  t("jira-get-boards", "Get All Boards", "jira", "Jira",
    "List all Jira boards", "Use get_all_boards to list all boards."),
  t("jira-get-board-issues", "Get Board Issues", "jira", "Jira",
    "Get issues on a board", "Use get_board_issues for board <board_id>."),
  t("jira-upload-attachment", "Upload Attachment", "jira", "Jira",
    "Upload an attachment to an issue", "Use upload_attachment to attach a file to issue <issue_key>."),
  t("jira-list-custom-fields", "List Custom Fields", "jira", "Jira",
    "List Jira custom fields", "Use list_custom_fields to list all custom fields."),
  t("jira-create-filter", "Create Filter", "jira", "Jira",
    "Create a Jira filter", "Use create_filter with name and JQL query."),

  // ── Webex ───────────────────────────────────────────────────────────
  t("webex-post-message", "Send Message", "webex", "Webex",
    "Send a Webex message", "Use post_message to send a message to room ${WEBEX_ROOM_ID}.\nFormat content in Markdown."),
  t("webex-create-room", "Create Room", "webex", "Webex",
    "Create a Webex room", "Use create_room to create a new room named \"<room_name>\"."),
  t("webex-add-users", "Add Users to Room", "webex", "Webex",
    "Add users to a Webex room", "Use add_users_to_room to add <email> to room <room_id>."),
  t("webex-list-rooms", "List Rooms", "webex", "Webex",
    "List Webex rooms", "Use list_rooms to list accessible Webex rooms."),
  t("webex-list-messages", "List Messages in Room", "webex", "Webex",
    "List messages in a Webex room", "Use list_messages_in_room for room <room_id>."),
  t("webex-list-users", "List Users in Room", "webex", "Webex",
    "List users in a Webex room", "Use list_users_in_room for room <room_id>."),
  t("webex-list-direct", "List Direct Messages", "webex", "Webex",
    "List direct messages with a user", "Use list_direct_messages for user <person_id>."),
  t("webex-list-thread", "List Thread Messages", "webex", "Webex",
    "List messages in a thread", "Use list_thread_messages for thread <message_id> in room <room_id>."),

  // ── ArgoCD ──────────────────────────────────────────────────────────
  t("argocd-list-apps", "List Applications", "argocd", "ArgoCD",
    "List ArgoCD applications", "Use list_applications to list all ArgoCD applications."),
  t("argocd-get-app", "Get Application Details", "argocd", "ArgoCD",
    "Get ArgoCD application details", "Use get_application_details for application <app_name>."),
  t("argocd-create-app", "Create Application", "argocd", "ArgoCD",
    "Create an ArgoCD application", "Use create_application with name, repo URL, path, and destination cluster/namespace."),
  t("argocd-update-app", "Update Application", "argocd", "ArgoCD",
    "Update an ArgoCD application", "Use update_application to update application <app_name>."),
  t("argocd-delete-app", "Delete Application", "argocd", "ArgoCD",
    "Delete an ArgoCD application", "Use delete_application to delete application <app_name>."),
  t("argocd-sync-app", "Sync Application", "argocd", "ArgoCD",
    "Sync an ArgoCD application", "Use sync_application to trigger a sync for application <app_name>."),
  t("argocd-list-projects", "List Projects", "argocd", "ArgoCD",
    "List ArgoCD projects", "Use project_list to list all ArgoCD projects."),
  t("argocd-create-project", "Create Project", "argocd", "ArgoCD",
    "Create an ArgoCD project", "Use project_create to create project <project_name>."),
  t("argocd-get-project", "Get Project", "argocd", "ArgoCD",
    "Get ArgoCD project details", "Use project_get for project <project_name>."),
  t("argocd-list-appsets", "List ApplicationSets", "argocd", "ArgoCD",
    "List ArgoCD ApplicationSets", "Use applicationset_list to list all ApplicationSets."),
  t("argocd-create-appset", "Create ApplicationSet", "argocd", "ArgoCD",
    "Create an ArgoCD ApplicationSet", "Use applicationset_create with the ApplicationSet spec."),
  t("argocd-list-clusters", "List Clusters", "argocd", "ArgoCD",
    "List ArgoCD clusters", "Use cluster_service__list to list all registered clusters."),
  t("argocd-get-cluster", "Get Cluster", "argocd", "ArgoCD",
    "Get ArgoCD cluster details", "Use cluster_service__get for cluster <cluster_name>."),
  t("argocd-pod-logs", "Get Pod Logs", "argocd", "ArgoCD",
    "Get pod logs from an application", "Use application_service__pod_logs for app <app_name>, pod <pod_name>."),
  t("argocd-search", "Search Resources", "argocd", "ArgoCD",
    "Search ArgoCD resources", "Use search_argocd_resources with query \"<query>\"."),
  t("argocd-check-perm", "Check Permission", "argocd", "ArgoCD",
    "Check if action is allowed", "Use account_service__can_i to check permission for <action> on <resource>."),

  // ── AI Gateway ──────────────────────────────────────────────────────
  t("aigateway-create-key", "Create LLM API Key", "aigateway", "AI Gateway",
    "Create or update an LLM API key", "Use create_llm_api_key for user <email>.\nWrite the key to /apikey_result.txt."),
  t("aigateway-get-spend", "Get User Spend", "aigateway", "AI Gateway",
    "Get user LLM usage and spend", "Use get_user_spend_activity for user <email>."),
  t("aigateway-list-models", "List Available Models", "aigateway", "AI Gateway",
    "List available LLM models", "Use list_available_models to list all available providers and models."),

  // ── AWS ─────────────────────────────────────────────────────────────
  t("aws-eks-manage", "Manage EKS Cluster", "aws", "AWS",
    "Manage an EKS cluster", "Use the EKS MCP to manage cluster <cluster_name> in region <region>."),
  t("aws-cost-analysis", "Cost Analysis", "aws", "AWS",
    "Analyze AWS costs", "Use the Cost Explorer MCP to analyze costs for account <account>."),
  t("aws-iam-check", "IAM Check", "aws", "AWS",
    "Check IAM permissions", "Use the IAM MCP to verify permissions for user/role <identity>."),

  // ── Backstage ───────────────────────────────────────────────────────
  t("backstage-search-entities", "Search Entities", "backstage", "Backstage",
    "Search Backstage entities", "Use get_entities_by_query with query \"<query>\"."),
  t("backstage-get-techdocs", "Get TechDocs Page", "backstage", "Backstage",
    "Get a TechDocs documentation page", "Use get_techdocs_page for entity <namespace>/<kind>/<name>, page <path>."),
  t("backstage-search-techdocs", "Search TechDocs", "backstage", "Backstage",
    "Search TechDocs documentation", "Use search_techdocs with query \"<query>\"."),
  t("backstage-list-techdocs", "List TechDocs Entities", "backstage", "Backstage",
    "List entities with TechDocs", "Use list_entities_with_techdocs to find entities that have documentation."),

  // ── Slack ───────────────────────────────────────────────────────────
  t("slack-post-message", "Post Message", "slack", "Slack",
    "Post a Slack message", "Use post_message to send a message to channel <channel_id>."),
  t("slack-reply-thread", "Reply to Thread", "slack", "Slack",
    "Reply in a Slack thread", "Use reply_to_thread in channel <channel_id>, thread <thread_ts>."),
  t("slack-list-channels", "List Channels", "slack", "Slack",
    "List Slack channels", "Use list_channels to list accessible Slack channels."),
  t("slack-get-channel-info", "Get Channel Info", "slack", "Slack",
    "Get Slack channel info", "Use get_channel_info for channel <channel_id>."),
  t("slack-list-messages", "List Messages", "slack", "Slack",
    "List messages in a channel", "Use list_messages for channel <channel_id>."),
  t("slack-upload-file", "Upload File", "slack", "Slack",
    "Upload a file to Slack", "Use upload_file to upload a file to channel <channel_id>."),
  t("slack-list-users", "List Users", "slack", "Slack",
    "List Slack users", "Use list_users to list all Slack users."),
  t("slack-get-user-info", "Get User Info", "slack", "Slack",
    "Get Slack user info", "Use get_user_info for user <user_id>."),
  t("slack-add-reaction", "Add Reaction", "slack", "Slack",
    "Add a reaction to a message", "Use add_reaction to add :<emoji>: to message <timestamp> in channel <channel_id>."),

  // ── PagerDuty ───────────────────────────────────────────────────────
  t("pd-get-incidents", "Get Incidents", "pagerduty", "PagerDuty",
    "Get PagerDuty incidents", "Use get_incidents to list current incidents."),
  t("pd-create-incident", "Create Incident", "pagerduty", "PagerDuty",
    "Create a PagerDuty incident", "Use create_incident with title and service <service_id>."),
  t("pd-acknowledge", "Acknowledge Incident", "pagerduty", "PagerDuty",
    "Acknowledge a PagerDuty incident", "Use acknowledge_incident for incident <incident_id>."),
  t("pd-resolve", "Resolve Incident", "pagerduty", "PagerDuty",
    "Resolve a PagerDuty incident", "Use resolve_incident for incident <incident_id>."),
  t("pd-get-services", "Get Services", "pagerduty", "PagerDuty",
    "List PagerDuty services", "Use get_services to list all PagerDuty services."),
  t("pd-get-oncalls", "Get On-Calls", "pagerduty", "PagerDuty",
    "Get on-call schedule", "Use get_oncalls to get current on-call information."),
  t("pd-get-schedules", "Get Schedules", "pagerduty", "PagerDuty",
    "List PagerDuty schedules", "Use get_schedules to list all schedules."),

  // ── Splunk ──────────────────────────────────────────────────────────
  t("splunk-search-logs", "Search Logs", "splunk", "Splunk",
    "Search Splunk logs", "Use search_splunk_logs with query \"<spl_query>\"."),
  t("splunk-get-incidents", "Get Incidents", "splunk", "Splunk",
    "Get Splunk incidents", "Use retrieve__incidents to list incidents."),
  t("splunk-create-detector", "Create Detector", "splunk", "Splunk",
    "Create a Splunk detector", "Use create__single__detector with the detector definition."),
  t("splunk-get-detectors", "Get Detectors", "splunk", "Splunk",
    "List Splunk detectors", "Use retrieve__detectors__query to list detectors."),
  t("splunk-create-team", "Create Team", "splunk", "Splunk",
    "Create a Splunk team", "Use create__single__team with name <team_name>."),
  t("splunk-get-indexes", "Get Indexes", "splunk", "Splunk",
    "List Splunk indexes", "Use get_splunk_indexes to list available indexes."),
  t("splunk-create-muting-rule", "Create Muting Rule", "splunk", "Splunk",
    "Create a Splunk muting rule", "Use create__single__muting__rule with the rule definition."),

  // ── Komodor ─────────────────────────────────────────────────────────
  t("komodor-search-services", "Search Services", "komodor", "Komodor",
    "Search Komodor services", "Use post_api_v2_svcs_search to search services."),
  t("komodor-search-issues", "Search Service Issues", "komodor", "Komodor",
    "Search service issues", "Use post_api_v2_svcs_issues_search to find service issues."),
  t("komodor-get-clusters", "Get Clusters", "komodor", "Komodor",
    "List Komodor clusters", "Use get_api_v2_clusts to list all clusters."),
  t("komodor-get-svc-yaml", "Get Service YAML", "komodor", "Komodor",
    "Get service YAML definition", "Use get_api_v2_svc_yaml for service <service_id>."),
  t("komodor-health-risks", "Get Health Risks", "komodor", "Komodor",
    "Get cluster health risks", "Use get_health_risks to list current health risks."),
  t("komodor-audit-log", "Get Audit Log", "komodor", "Komodor",
    "Get Komodor audit log", "Use get_api_v2_audit_log to retrieve the audit log."),
  t("komodor-trigger-rca", "Trigger RCA", "komodor", "Komodor",
    "Trigger a root cause analysis", "Use post_trigger_klaudia_rca for service <service_name>."),
  t("komodor-cost", "Get Cost Allocation", "komodor", "Komodor",
    "Get cost allocation data", "Use get_cost_allocation to get cost data."),

  // ── Confluence ──────────────────────────────────────────────────────
  t("confluence-get-pages", "Get Pages", "confluence", "Confluence",
    "List Confluence pages", "Use get_pages to list pages in space <space_key>."),
  t("confluence-create-page", "Create Page", "confluence", "Confluence",
    "Create a Confluence page", "Use create_page in space <space_key> with title and body."),
  t("confluence-update-page", "Update Page", "confluence", "Confluence",
    "Update a Confluence page", "Use update_page for page <page_id> with new content."),
  t("confluence-get-spaces", "Get Spaces", "confluence", "Confluence",
    "List Confluence spaces", "Use get_spaces to list all accessible spaces."),
  t("confluence-create-space", "Create Space", "confluence", "Confluence",
    "Create a Confluence space", "Use create_space with key <space_key> and name <space_name>."),
  t("confluence-get-blog-posts", "Get Blog Posts", "confluence", "Confluence",
    "List Confluence blog posts", "Use get_blog_posts for space <space_key>."),
  t("confluence-create-blog", "Create Blog Post", "confluence", "Confluence",
    "Create a Confluence blog post", "Use create_blog_post in space <space_key> with title and body."),
  t("confluence-add-labels", "Add Labels", "confluence", "Confluence",
    "Add labels to content", "Use add_labels_to_content for content <content_id> with labels."),
  t("confluence-add-comment", "Add Comment", "confluence", "Confluence",
    "Add a comment to a page", "Use create_footer_comment on page <page_id> with comment body."),

  // ── Utility / Built-in ──────────────────────────────────────────────
  t("util-read-file", "Read File", "github", "Utility",
    "Read a local file", "Use read_file to read /path/to/file.\nWrite results to /output.txt."),
  t("util-write-file", "Write File", "github", "Utility",
    "Write content to a local file", "Use write_file to write content to /path/to/file."),
  t("util-terraform-fmt", "Format Terraform", "github", "Utility",
    "Format a Terraform file", "Read /input.tf.\nApply terraform_fmt to format as valid HCL.\nWrite to /formatted.tf."),
  t("util-fetch-url", "Fetch URL", "github", "Utility",
    "Fetch content from a URL", "Use fetch_url to retrieve content from <url>.\nWrite the response to /fetched.txt."),
  t("util-jq", "Process JSON (jq)", "github", "Utility",
    "Process JSON with jq", "Use jq with filter \"<filter>\" on /input.json.\nWrite results to /output.json."),
  t("util-yq", "Process YAML (yq)", "github", "Utility",
    "Process YAML with yq", "Use yq with expression \"<expr>\" on /input.yaml.\nWrite results to /output.yaml."),
  t("util-git", "Run Git Command", "github", "Utility",
    "Run a git command", "Use git to run: git <command>."),
  t("util-invoke-task", "Invoke Self-Service Task", "github", "Utility",
    "Invoke another self-service task", "Use invoke_self_service_task to trigger task \"<task_name>\"."),
  ];
}

/** @deprecated Use {@link getStepTemplates} for dynamic APP_NAME resolution. */
export const STEP_TEMPLATES: StepTemplate[] = getStepTemplates();

export function getTemplatesByCategory(): Record<string, StepTemplate[]> {
  return getStepTemplates().reduce<Record<string, StepTemplate[]>>((acc, t) => {
    if (!acc[t.category]) acc[t.category] = [];
    acc[t.category].push(t);
    return acc;
  }, {});
}
